services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: ["5432:5432"]
    volumes: 
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./lab_1:/lab_1
      - ./lab_2:/lab_2
      - ./lab_3:/lab_3
      # - ./lab_4:/lab_4
      # - ./lab_5:/lab_5
      # - ./lab_6:/lab_6
volumes:
  pg_data:
